export const topCasinos = [
  {
    id: 1,
    rank: 1,
    name: "BetMGM Casino",
    logo: "🎰",
    rating: 4.9,
    trustScore: 98,
    welcomeBonus: "$1000",
    freeSpins: "200",
    minDeposit: "$10",
    payoutSpeed: "1-3 days",
    gameCount: "2500+",
    license: "New Jersey Gaming Commission",
    established: "2018",
    features: ["24/7 Support", "Mobile App", "Live Chat", "VIP Program"],
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Bank Transfer", "Apple Pay"],
    popularGames: ["Blackjack", "Roulette", "Slots", "Poker", "Baccarat"],
    pros: ["Excellent game variety", "Fast withdrawal processing", "Strong mobile app", "Trusted brand name"],
    gameProviders: ["NetEnt", "Microgaming", "Evolution", "Pragmatic Play"],
    restrictions: "NJ, PA, MI, WV residents only",
    maxPayout: "$500,000",
    rtp: "96.5%",
    currencies: ["USD"],
    languages: ["English"],
    customerSupport: "24/7 Live Chat, Email, Phone",
  },
  {
    id: 2,
    rank: 2,
    name: "Caesars Palace Online",
    logo: "👑",
    rating: 4.8,
    trustScore: 99,
    welcomeBonus: "$2500",
    freeSpins: "0",
    minDeposit: "$20",
    payoutSpeed: "2-5 days",
    gameCount: "1800+",
    license: "Nevada Gaming Control Board",
    established: "2013",
    features: ["VIP Rewards", "Live Dealer", "Mobile Optimized", "Exclusive Games"],
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Play+", "Bank Transfer"],
    popularGames: ["Baccarat", "Craps", "Video Poker", "Slots", "Roulette"],
    pros: [
      "Prestigious brand reputation",
      "Generous welcome package",
      "Exclusive VIP program",
      "High-quality live dealer games",
    ],
    gameProviders: ["IGT", "NetEnt", "Evolution", "Playtech"],
    restrictions: "NV, NJ, PA, MI residents only",
    maxPayout: "$1,000,000",
    rtp: "96.8%",
    currencies: ["USD"],
    languages: ["English"],
    customerSupport: "24/7 Live Chat, Email, Phone",
  },
  {
    id: 3,
    rank: 3,
    name: "DraftKings Casino",
    logo: "🏆",
    rating: 4.7,
    trustScore: 96,
    welcomeBonus: "$2000",
    freeSpins: "0",
    minDeposit: "$5",
    payoutSpeed: "1-2 days",
    gameCount: "1200+",
    license: "Pennsylvania Gaming Control Board",
    established: "2020",
    features: ["Sportsbook Integration", "Daily Promotions", "Mobile First", "Quick Deposits"],
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Apple Pay", "Google Pay"],
    popularGames: ["Daily Fantasy", "Slots", "Blackjack", "Roulette", "Video Poker"],
    pros: ["Low minimum deposit", "Quick payouts", "Great mobile experience", "Integration with sportsbook"],
    gameProviders: ["NetEnt", "IGT", "SG Digital", "Evolution"],
    restrictions: "NJ, PA, MI, WV residents only",
    maxPayout: "$250,000",
    rtp: "96.2%",
    currencies: ["USD"],
    languages: ["English"],
    customerSupport: "24/7 Live Chat, Email",
  },
  {
    id: 4,
    rank: 4,
    name: "Golden Nugget Online",
    logo: "💰",
    rating: 4.6,
    trustScore: 95,
    welcomeBonus: "$1500",
    freeSpins: "200",
    minDeposit: "$10",
    payoutSpeed: "1-3 days",
    gameCount: "1500+",
    license: "New Jersey Division of Gaming Enforcement",
    established: "2013",
    features: ["Live Dealer", "Progressive Jackpots", "Mobile App", "Loyalty Program"],
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Play+", "ACH"],
    popularGames: ["Slots", "Blackjack", "Roulette", "Baccarat", "Pai Gow"],
    pros: ["Strong game selection", "Reliable payments", "Good customer service", "Progressive jackpots"],
    gameProviders: ["NetEnt", "IGT", "Evolution", "Red Tiger"],
    restrictions: "NJ, PA, MI residents only",
    maxPayout: "$500,000",
    rtp: "96.3%",
    currencies: ["USD"],
    languages: ["English"],
    customerSupport: "24/7 Live Chat, Email, Phone",
  },
  {
    id: 5,
    rank: 5,
    name: "FanDuel Casino",
    logo: "🎲",
    rating: 4.5,
    trustScore: 94,
    welcomeBonus: "$1000",
    freeSpins: "0",
    minDeposit: "$10",
    payoutSpeed: "2-4 days",
    gameCount: "1000+",
    license: "Pennsylvania Gaming Control Board",
    established: "2019",
    features: ["Same Game Parlay", "Live Betting", "Cash Out", "Daily Promotions"],
    paymentMethods: ["Visa", "Mastercard", "PayPal", "FanDuel Play+", "Online Banking"],
    popularGames: ["Slots", "Blackjack", "Roulette", "Craps", "Video Poker"],
    pros: ["User-friendly interface", "Good promotional offers", "Reliable platform", "Sports betting integration"],
    gameProviders: ["NetEnt", "IGT", "Evolution", "WMS"],
    restrictions: "NJ, PA, MI, WV residents only",
    maxPayout: "$1,000,000",
    rtp: "96.1%",
    currencies: ["USD"],
    languages: ["English"],
    customerSupport: "24/7 Live Chat, Email",
  },
];
const filterOptions = [
  "All Casinos",
  "Highest Rated",
  "Best Bonuses",
  "Fastest Payouts",
  "Mobile Friendly",
  "Live Dealer",
  "New Casinos",
];
export default topCasinos;
